name: ib_manifest_env
channels:
  - conda-forge
  - default
dependencies:
  - click
  # - conda-vendor
  - jinja2
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - python
  - requests
  - ruamel.yaml
  - urllib3
  - pip:
    - -e .
    # remove when conda-vendor 1.0.3 is on conda-forge
    - conda-vendor
