name: ib_manifest_env
channels:
  - conda-forge
  - default
dependencies:
  - click
  # - conda-vendor
  - jinja2
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - python
  - requests
  - ruamel.yaml
  - urllib3
  - pip:
    - -e .
    - conda-vendor
