name: Test deployment

on:
  pull_request:
    branches:
    - main
    - dev
    paths:
    - documentation/**
    - .github/workflows/docs-deploy.yml
    - .github/workflows/docs-test-deploy.yml
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

defaults:
  run:
    shell: bash
    working-directory: documentation

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: documentation/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: yarn build
