name: Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install conda dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          activate-environment: ib_manifest_env
          environment-file: environment.yml
          auto-activate-base: true

      - name: Install package
        run: |
          pip install -e .

      - name: Conda list
        run: conda list

      - name: Test with pytest
        run: |
          pytest tests -vvv --cov=ib_manifest_util
